Add namespace for this project.
This project is for non-general use interfaces, so this namespace
makes sure it can only be used on devices that include it.

Devices can include this by adding:
PRODUCT_SOONG_NAMESPACES := hardware/google/interfaces
to their configuration.

Bug: 72879006
Test: m nothing
Test: adding a module to this directory isn't seen by other modules
    example error:
error: system/tools/hidl/Android.bp:72:1: "libhidl-gen" depends on undefined module "secret_defaults"
Module "libhidl-gen" is defined in namespace "." which can read these 1 namespaces: ["."]
Module "secret_defaults" can be found in these namespaces: ["hardware/google/interfaces"]

Change-Id: I8cdd53e123a084fee532d34edb6efc5c4c69e367